name: Coverage

on: [workflow_dispatch]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch:

jobs:
  coverage:
    name: Test Coverage
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync

    - name: Build extension
      run: |
        uv sync --reinstall-package coremusic

    - name: Run tests with coverage
      run: |
        uv run pytest -m "not slow" \
          --cov=coremusic \
          --cov-report=xml \
          --cov-report=term-missing \
          --cov-report=html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-coremusic
        fail_ci_if_error: false
      continue-on-error: true

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ github.sha }}
        path: htmlcov/
        retention-days: 30

    - name: Coverage Summary
      run: |
        echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY || true

    - name: Check coverage threshold
      run: |
        COVERAGE=$(uv run coverage report | grep TOTAL | awk '{print $NF}' | sed 's/%//')
        echo "Current coverage: ${COVERAGE}%"
        if (( $(echo "$COVERAGE < 75" | bc -l) )); then
          echo "::warning::Coverage is below 75% threshold (current: ${COVERAGE}%)"
        fi
      continue-on-error: true
